apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ballot
  name: ballot
spec: 
  selector: 
    app: ballot
  ports:
  - name: ballot
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
    spec:
      containers:
      - name: ballot
        image: shakulmittal/private:v1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-secret
      - name: secret-1
      - name: secret-2
